:toc: macro

= Threshold cross-chain - Arbitrum

This package brings Bitcoin to Ethereum L2 Arbitrum. For more details please
see link:https://github.com/keep-network/tbtc-v2/blob/main/docs/rfc/rfc-8.adoc[Cross-chain Tokenized Threshold BTC]

== How it works?

```
+----------------------------+         +---------------------------------------------------------------------------+
|          Ethereum          |         |                                Arbitrum                                   |
|                            |         |                                                                           |
|  +----------------------+  |         |  +----------------------+  +-------------------------+  +--------------+  |
|  | Wormhole TokenBridge |--|---------|--| Wormhole TokenBridge |--| ArbitrumWormholeGateway |--| ArbitrumTBTC |  |
|  +----------------------+  |         |  +----------------------+  +-------------------------+  +--------------+  |
|                            |         |                                                                           |
+----------------------------+         +---------------------------------------------------------------------------+
```

- `ArbitrumTBTC` canonical tBTC token on Arbitrum with a minting authority
delegated to `ArbitrumWormholeGateway`.
- `ArbitrumWormholeGateway` is a smart contract wrapping and unwrapping 
Wormhole-specific tBTC representation into the canonical `ArbitrumTBTC` token.

=== Deploy contracts

To deploy all contracts on the given network, please run:
```
yarn deploy --network <network>
```

If contracts haven't been built yet or changes occurred, this task will build
the contracts before running the deployment script. This command produces
an `export.json` file containing contract deployment info. Note that for the
chains other than 'hardhat' the following env. variables are needed:

- `CHAIN_L2_API_URL` - URL to access blockchain services, e.g. `\https://arb-goerli.g.alchemy.com/v2/<alchemy_api_key>`
- `CONTRACT_L2_OWNER_ADDRESS` - Deployer / Contract Owner address
- `THRESHOLD_L2_COUNCIL_ADDRESS` - Council / Governance address
- `ACCOUNTS_L2_PRIVATE_KEYS` - Private keys for the deployer and council `<0xOwnerPrivKey,0xCouncilPrivKey>`
- `ARBISCAN_API_KEY` - Arbiscan API key
