= TBTC v2

== Abstract

For many Bitcoin holders, one question remains: how can I move my assets across
blockchains to make them more useful while maintaining Bitcoin's core values?

Existing solutions that bridge Bitcoin to Ethereum require users to send their
Bitcoin to an intermediary in exchange for an Ethereum token that represents the
original asset. This centralized model requires you to trust a third party and
is prone to censorship, threatening Bitcoin's promise of secure, permissionless
decentralization.

Threshold aims to solve this problem with TBTC v2.

The second generation of TBTC is a truly decentralized bridge between Bitcoin
and Ethereum. It provides Bitcoin holders permissionless access to DeFi and the
expanding web3 universe.

TBTC v2 replaces centralized intermediaries with a randomly selected group of
node operators on the Threshold Network. This group of independent operators
works together to secure your deposited Bitcoin through threshold cryptography.
That means TBTC v2 requires a majority threshold agreement before operators
perform any action with your Bitcoin. By rotating the selection of operators,
TBTC v2 protects against any malicious individual or group of operators seizing
control. Unlike other solutions on the market, users on TBTC v2 are reliant on
math, not hardware or people. Additionally, TBTC v2 is open and accessible to
anyone.
  
TBTC v2 allows anyone to use Bitcoin in the expanding DeFi and Web3 universe
without a third-party intermediary. 

== System Architecture

=== Upgradeability

`Bank` is a central, non-upgradeable contract keeping track of Bitcoin balances. 

`Bridge` is deployed behind a `TransaprentUpgradeableProxy` and can be upgraded
by a `ProxyAdmin`, eventually Threshold DAO.

`TBTCVault` upgrade happens in two steps with a 24-hour governance delay. The
owner of `TBTCVault` can initiate and finalize an upgrade to another vault.
The new vault receives ownership of TBTC token as well as the entire `TBTCVault`
balance in the Bank.