name = "tbtc-deposit-reveals"
main = "./src/index.ts"
compatibility_date = "2022-10-10"

[[d1_databases]]
binding = "DB"
database_name = "tbtc-deposit-reveals-staging"
database_id = "144880b2-3392-4e24-afa2-453d6940b9f7"

# Staging
[[env.staging.d1_databases]]
binding = "DB"
database_name = "tbtc-deposit-reveals-staging"
database_id = "144880b2-3392-4e24-afa2-453d6940b9f7"

# Production
[[env.production.d1_databases]]
binding = "DB"
database_name = "tbtc-deposit-reveals-production"
database_id = "a859f79c-2a13-4e71-8602-c0a1098a3303"
