:toc: macro

= RFC 7: Sweeping coordination

:icons: font
:numbered:
toc::[]

== Background

Before generating tECDSA signature, the off-chain client software needs to agree
in the signing group on the message being signed. In tBTC v2, the information
needed to evaluate the signed message comes from multiple sources that might not
be ideally synced with each other. Moreover, it is not possible to establish a
precise point in time based on which the information should be retrieved.

=== Current Functionality

In tBTC v1, the message to be signed is calculated on-chain
link:https://github.com/keep-network/tbtc/blob/d18ef9aec7656f0ec7d317ece3e3d5c7aca92cda/solidity/contracts/deposit/DepositRedemption.sol#L133-L160[during the redemption request]
and link:https://github.com/keep-network/tbtc/blob/d18ef9aec7656f0ec7d317ece3e3d5c7aca92cda/solidity/contracts/deposit/DepositRedemption.sol#L291-L316[when increasing the redemption fee].
Every single deposit is under a separate P2WPKH address and is confirmed with
SPV proof. This, plus the fact the redemption can be done only one time for the
given deposit makes it possible to generate the message to be signed on-chain
and does not require additional coordination between signing group members. The
signing group members do not have to worry about confirming the P2WPKH deposit
transaction on Bitcoin because it is covered by the SPV on-chain proof submitted
to Ethereum by the depositor.

This approach is easy to integrate with off-chain client software but is way
more expensive on-chain compared to the approach taken by tBTC v2.

In tBTC v2, 51-of-100 tECDSA-backed wallets accept multiple deposits. Depositors
send BTC to the most-recently-created-wallet using P2SH transaction and reveal
their deposit transaction to Ethereum chain. The off-chain client software must
listen for these sorts of events and periodically check the Bitcoin network to
ensure P2SH deposits are sufficiently confirmed. If everything checks out, the
off-chain client software should coordinate to produce a signature and perform
a sweeping Bitcoin transaction that is confirmed on Ethereum with SPV proof and
updates depositors' balances in the Bridge.

This approach is more cost-effective: it allows to split of the cost of SPV
proof between multiple depositors and does not require expensive signing group
key generation for every single deposit. Yet, it requires the off-chain client
software to coordinate - before producing a signature - to decide which deposits
should be swept and with what Bitcoin network fee.

== Proposal

This document aims at describing a protocol for reaching an agreement about the
Bitcoin sweep transaction between the signing group members.

=== Goal

The protocol should tolerate small differences in the state of the world, as
seen by individual signing group members. It should be compatible with a light
relay, and support signing retries. All transactions must be sufficiently
confirmed and the transaction being signed must adhere to the recent Bitcoin
network fees.

==== Sufficiently confirmed transactions

The P2SH transactions on Bitcoin must be sufficiently confirmed (at least 6
confirmations) before they are eligible for sweeping. The deposit reveal
transactions on Ethereum must be sufficiently confirmed (at least 20
confirmations) before they are eligible for sweeping.

==== No order guaranteed

There is no guarantee which transaction gets a sufficient number of
confirmations first: Bitcoin P2SH deposit transaction or Ethereum deposit reveal
transactions. The order in which P2SH deposit transactions gets confirmed on
Bitcoin does not need to correspond to the order in which deposit reveal
transaction gets confirmed on Ethereum. There is also no guarantee that the
Ethereum reveal transaction points to an existing Bitcoin P2SH transaction.

==== State differences

Every tBTC v2 client software instance is connected to different Ethereum and
Bitcoin clients. Ethereum clients in the network will have a slightly different
synchronization state at any given point in time. Bitcoin clients in the network
will also have a slightly different synchronization state. Since the light relay
is not submitting all Bitcoin headers to Ethereum, there is no way to reference
from Ethereum to a fixed point in time on Bitcoin. We must accept all tBTC v2
client software will have a slightly different view of the world at any point in
time.

==== Adhere to network conditions

The Bitcoin sweep transaction must have a fee that allows it to be mined in a
reasonable time. If the Bitcoin network conditions change, there must be a
mechanism to increase the fee and replace transactions. The wallet must finish
the current operation before attempting another one.

==== Retries

The tECDSA protocol used for signing must be able to retry in case some signing
group members are offline or corrupted. The tBTC v2 client software should join
the pending signing after the client restart.

=== Implementation

==== Coordinator

We introduce a rotating role of Coordinator responsible for proposing a sweep
Bitcoin transaction. The role of Coordinator rotates every 6 hours across all
operators in the group. For example, if the group consist of the following
members: `[0xA, 0xB, 0xC, 0xC, 0xB, 0xD`] the rotation rounds are: `0xA, 0xB,
0xC, 0xD`. The rotation schedule begins at UNIX epoch (00:00:00 UTC on 1 January
1970).

==== Sweeping schedule

Sweep can only be proposed by the current Coordinator. The Coordinator can only
propose a sweep between:

- 00:00 UTC - 01:00 UTC
- 08:00 UTC - 09:00 UTC
- 16:00 UTC - 17:00 UTC

If the current Coordinator does not propose a sweep within the given time
window, the attempt is skipped.