:toc: macro

= RFC 1: tBTCv2 Design

:icons: font
:numbered:
toc::[]

== Overview

=== Minting

Stakers periodically create 51-of-100 (subject to change) ecdsa-backed wallets
to hold frozen BTC assets to maintain the peg. Depositors send BTC funds to the
most-recently-created-wallet by using pay-to-script-hash (P2SH) which contains
hashed information about the depositor's minting ethereum address. Once the
block is mined, the depositor reveals their desired ethereum minting address to
the ethereum chain. The TBTC system listens for these sorts of messages and
when it gets one, it checks the bitcoin network to make sure the funds line up.
If everything checks out, then we mint!

=== Redemption

A user supplies tBTCv2 and a bitcoin address. The system burns the tBTCv2 and
releases the equivalent amount of bitcoin to the user from the oldest
outstanding bitcoin wallet. If the oldest does not have enough, the remaining
balance carries over to the next oldest until an equivalent amount of BTC has
been released.

=== Continuous Fees

The system is able to collect fees in the form of tBTC when the BTC is
deposited and when it is redeemed. Rather than paying operators at those two
instances we would prefer to pay them continuously. Since we do not have the
tBTC to pay them with until we collect the redemption fee (and can't mint it
and maintain the peg), we must turn to another token. Instead, the system pays
operators continuously in mintable T tokens and whenever it collects tBTC fees
it uses those fees to buy T tokens back for its treasury.

== In Depth

=== Minting

==== Deposit + Commitment

Once we know the active wallet's public key hash, the dApp can put together a
pay-to-script-hash (P2SH) address to receive the funds. This script will be
unique to each depositor and will look like:

```
<eth-address> DROP
<blinding-factor> DROP
DUP HASH160 <signingGroupPubkey> EQUAL
IF
  CHECKSIG
ELSE
  DUP HASH160 <refundPubkey> EQUALVERIFY
  <locktime> CHECKLOCKTIMEVERIFY DROP
  CHECKSIG
ENDIF
```

Since each depositor has their own ethereum address and their own secret
blinding factor (which is an additional security layer), each depositor's
script will be unique, and the hash of each depositor's script will be unique.

In order to unlock the funds, one must provide the unhashed script, (which
means that they know the eth address and blinding factor), as well as an
unlocking script with a signature and public key. If the sig+pubkey matches the
signing group public key, the funds are able to be moved immediately. If the
sig+pubkey matches the refund public key, then the funds can be moved after 30
days (specified as `locktime`).

==== The Big Reveal

After the deposit transaction has been mined, the user is able to reveal their
ethereum address and blinding factor to the ethereum chain. The TBTC system listens
for these sorts of messages and when it sees one, is able to generate a script that
can spend the funds. Once successful, wallet moves the funds from the P2SH
address to the main wallet address, which allows the system to mint tBTC and
disables the 30-day refund.

==== Automated Refunds

A bitcoin transaction is an amount and a script. The script can be something as
simple as "these funds can be spent by wallet 0xabc", or in our case, as
complex as "these funds can be spent by wallet 0xabc but if they aren't spent
within 30 days they can be spent by wallet 0x123". This gives us the ability to
create deposits that automatically are refunded after 30 days if they aren't
swept. Thus, if a user misfunds or they get cold feet (for any reason), all
they need to do is not submit their reveal and wait 30 days.

=== Redemption

To initiate a redemption, a user supplies an amount `x` of TBTC and a bitcoin
address. Then, the system calculates the redemption fee `fee`, and releases an
amount of bitcoin `y` such that `x = y + fee` to the supplied bitcoin address.
`y` amount of TBTC is burned to maintain the peg. The remaining `fee` TBTC is
sold by the system to buy back `T` tokens (more about this process in the fee
section).

In the MVP version of the system, a redemption is capped at the amount of
bitcoin contained in the largest wallet. Redemptions are fulfilled from the
oldest wallet that contains enough bitcoin to fulfil the redemption. If more
tBTC needs to be redeemed than there is in the largest wallet, then the user
needs to submit multiple redemptions. After a redemption, if a wallet has under
a governable threshhold of BTC remaining, it transfers that BTC to the active
wallet and closes.

=== Wallet Lifecycle

Wallets are periodically created, where the period length is a governable
parameter. To create a new wallet, a group of 100 operators is selected from
the pool of available operators (some operators may be selected twice if there
are not enough) using a process called sortition. The probabiliy that a
particular operator is chosen is based on their stake weight, which in turn is
based on the number of `T` tokens they have invested in the staking contract.

Once the 100 operators have been selected, they generate a 51-of-100 ecdsa
signing group to handle the bitcoin key material. The distributed key
generation process requires that all 100 participants are available, but future
signing events (like minting and redemption) only require 51 of the 100.

As time passes and operators drop out of the system, a wallet becomes at risk of
being able to meet the 51-of-100 threshhold to produce signatures. Additionally,
we want to avoid situations where operators are the custodians of a wallet for
extended periods. To avoid these issues, we can set a max age of a wallet and a minimum
liveness threshhold. Once a wallet is older than the max age, or if it drops below
the liveness threshhold (say, below 60 on a heartbeat), we motion to transfer
the funds to another randomly selected wallet.

Once a wallet no longer has funds and is not the primary wallet for new
deposits, it can be closed and operators are no longer required to maintain
it.

=== Heartbeats

To make sure that older wallets are still accessible for redemption, we need to
perform heartbeats. This can take the form of small, cheap work that can be
used to verify that a node is still able to provide its part in a 51-of-100
signing event.

// FIXME: figure out how this works
