:toc: macro

= RFC 7: Sweeping coordination

:icons: font
:numbered:
toc::[]

== Background

Before generating tECDSA signature, the off-chain client software needs to agree
in the signing group on the message being signed. In tBTC v2, the information
needed to evaluate the signed message comes from multiple sources that might not
be ideally synced with each other. Moreover, it is not possible to establish a
precise point in time based on which the information should be retrieved.

=== Current Functionality

In tBTC v1, the message to be signed is calculated on-chain
link:https://github.com/keep-network/tbtc/blob/d18ef9aec7656f0ec7d317ece3e3d5c7aca92cda/solidity/contracts/deposit/DepositRedemption.sol#L133-L160[during the redemption request]
and link:https://github.com/keep-network/tbtc/blob/d18ef9aec7656f0ec7d317ece3e3d5c7aca92cda/solidity/contracts/deposit/DepositRedemption.sol#L291-L316[when increasing the redemption fee].
Every single deposit is under a separate P2WPKH address and is confirmed with
SPV proof. This, plus the fact the redemption can be done only one time for the
given deposit makes it possible to generate the message to be signed on-chain
and does not require additional coordination between signing group members. The
signing group members do not have to worry about confirming the P2WPKH deposit
transaction on Bitcoin because it is covered by the SPV on-chain proof submitted
to Ethereum by the depositor.

This approach is easy to integrate with off-chain client software but is way
more expensive on-chain compared to the approach taken by tBTC v2.

In tBTC v2, 51-of-100 tECDSA-backed wallets accept multiple deposits. Depositors
send BTC to the most-recently-created-wallet using P2SH transaction and reveal
their deposit transaction to Ethereum chain. The off-chain client software must
listen for these sorts of events and periodically check the Bitcoin network to
ensure P2SH deposits are sufficiently confirmed. If everything checks out, the
off-chain client software should coordinate to produce signatures and perform
a sweeping Bitcoin transaction that is confirmed on Ethereum with SPV proof and
updates depositors' balances in the Bridge.

This approach is more cost-effective: it allows to split of the cost of SPV
proof between multiple depositors and does not require expensive signing group
key generation for every single deposit. Yet, it requires the off-chain client
software to coordinate - before producing signatures - to decide which deposits
should be swept and with what Bitcoin network fee.

== Proposal

This document aims at describing a protocol for reaching an agreement about the
Bitcoin sweep transaction between the signing group members.

=== Goal

The protocol should tolerate small differences in the state of the world, as
seen by individual signing group members. It should be compatible with a light
relay, and support signing retries. All transactions must be sufficiently
confirmed and the sweep transaction must adhere to the recent Bitcoin network
fees.

==== Sufficiently confirmed transactions

The P2SH transactions on Bitcoin must be sufficiently confirmed (at least 6
confirmations) before they are eligible for sweeping. The deposit reveal
transactions on Ethereum must be sufficiently confirmed (at least 20
confirmations) before they are eligible for sweeping.

==== No order guaranteed

There is no guarantee which transaction gets a sufficient number of
confirmations first: Bitcoin P2SH deposit transaction or Ethereum deposit reveal
transactions. The order in which P2SH deposit transactions gets confirmed on
Bitcoin does not need to correspond to the order in which deposit reveal
transaction gets confirmed on Ethereum. There is also no guarantee that the
Ethereum reveal transaction points to an existing Bitcoin P2SH transaction.

==== State differences

Every tBTC v2 client software instance is connected to different Ethereum and
Bitcoin clients. Ethereum clients in the network will have a slightly different
synchronization state at any given point in time. Bitcoin clients in the network
will also have a slightly different synchronization state. Since the light relay
is not submitting all Bitcoin headers to Ethereum, there is no way to reference
from Ethereum to a fixed point in time on Bitcoin. We must accept the fact that
all tBTC v2 client software will have a slightly different view of the world at
any point in time.

==== Adhere to network conditions

The Bitcoin sweep transaction must have a fee that allows it to be mined in a
reasonable time. If the Bitcoin network conditions change, there must be a
mechanism to increase the fee and replace transactions. The wallet must finish
the current operation before attempting another one.

==== Retries

The tECDSA protocol used for signing must be able to retry in case some signing
group members are offline or corrupted.

=== Implementation

==== Coordinator

We introduce a rotating role of Coordinator responsible for proposing a sweep
Bitcoin transaction. The role of Coordinator rotates every 8 hours across all
operators in the group. For example, if the group consist of the following
members: `[0xA, 0xB, 0xC, 0xC, 0xB, 0xD`] the rotation rounds are: `0xA, 0xB,
0xC, 0xD`. The rotation schedule begins at UNIX epoch (00:00:00 UTC on 1 January
1970).

==== Sweeping schedule

Sweep can only be proposed by the current Coordinator. The Coordinator can only
propose a sweep between:

- 00:00 UTC - 0:30 UTC
- 08:00 UTC - 08:30 UTC
- 16:00 UTC - 16:30 UTC

If the current Coordinator does not propose a sweep within the given time
window, the attempt is skipped.

The Coordinator must not propose a sweep if there is currently a pending signing
operation being executed by the wallet or if the last signed transaction from
the wallet does not have 6 Bitcoin confirmations yet.

The coordinator may slightly delay broadcasting the proposition to give all
clients in the group a chance to properly recognize a Coordinator rotation.

==== Sweep transaction

The Coordinator chooses sufficiently confirmed deposits for the sweep. To avoid
synchronization problems with deposits on the brink of being sufficiently
confirmed, the Coordinator may choose deposits with more than 6 confirmations
on Bitcoin and 20 confirmations on Ethereum. To avoid problems with proving
large transactions and too many signatures to be executed, the Coordinator
should not pick more than 10 deposits. The Coordinator chooses the Bitcoin
transaction fee reflecting the current situation in the Bitcoin network. To
leave enough time for retries, deposits for which Bitcoin transactions unlock
for a refund earlier than two weeks from now are skipped.

The Coordinator must not propose a sweep if there is currently a pending signing
operation being executed by the wallet or if the last transaction from the
wallet does not have 6 Bitcoin confirmations yet.

The Coordinator proposes a sweep over the wallet's broadcast channel.

All signing group members must confirm that all deposits in the proposed sweep
are sufficiently confirmed, that the maximum number of deposits is not exceeded,
that the proposed fee reflects the current situation in the Bitcoin network
plus/minus some margin, that all deposit UTXOs can be unlocked with the
wallet's public key, and that there is enough time to unlock UTXO before the
refund.

When proposing a sweep, the Coordinator sets the Ethereum block number at which
the signing protocol should start. All clients validate if that block's number
is +-2 blocks from the current one.

If all these requirements are met, the last transaction executed by the wallet
is sufficiently confirmed, and there is no other signing by the wallet in
progress, the signing group members proceed with tECDSA signing protocol.

The signing starts with the announcement phase where each signing group member
announces their readiness to participate in the signing of sweep transaction inputs.
51 signers from the ones who announced their readiness are selected for the
protocol. They unlock each deposit UTXO with a signature. Signatures are
computed in parallel and no signature should be completed without all others.
This approach simplifies defeating fraud proofs as this is all-or-nothing
situation for a sweep transaction signing. There is a timeout for unlocking all
inputs of the sweep transactions. If the timeout is exceeded, the retry is
executed. The retry starts with a new announcement phase to establish a set of
signers ready to execute the protocol.

```
|                  | ------------ signature 1 ------------> |                   |
| ... announce ... | ------------ signature 2 ------------> | protocol end      | timeout
|                  | ------------ signature 3 ------------> |                   |
```

==== Retries

The most computationally expensive part of the signing protocol takes 2 seconds
on a 10-core M1 machine for a single signing group member. Assuming the client
works on a 2-core machine and there are no more than 5 signing group members on
a single machine, the bottleneck phase should take no more than 1 minute. For
the sake of establishing a sufficient timeout, we assume a single signing should
take no more than 5 minutes not counting the announcement phase. It means that
all signatures for a sweep transaction with a maximum number of 10 inputs
should be completed in less than an hour.

The timeout for signing should be proportional to the number of inputs in the
sweep transaction.

The signing protocol is non-attributable and we need to retry in case of
corrupted data:

- With 2 malicious members in a signing group, we need 5 retries of the protocol
in the worst case (`P = (98 choose 51) / (100 choose 51) = 0.23757575757`),
which takes 5 hours for 10 inputs.
- With 3 malicious members in a signing group, we need 10 retries of the
protocol in the worst case (`P = (97 choose 51) / (100 choose 51) = 0.11393939393`),
which takes 10 hours for 10 inputs.
- With 4 malicious members in a signing group, we need 20 retries of the
protocol in the worst case (`P = (96 choose 51) / (100 choose 51) = 0.05403311465`),
which takes 20 hours for 10 inputs.

The signing that keeps failing is retried for no more than 48 hours. Since no
interim signatures were produced, it is safe to stop the signing without exposing
wallet for risk of being slashed for signature fraud.

No state management logic is required for retries other than keeping information
in-memory about the sweep transaction being signed. If more than t+1 clients get
restarted during the sweep transaction signing, the sweep attempt is skipped and
everyone needs to wait for another sweep window.

==== Increasing fee

At any point in time, the current Coordinator (who is not necessarily the same
Coordinator who proposed the batch) can propose increasing the Bitcoin fee for
the sweep transaction that is in the mempool. The signing group members sign the
transaction if the original transaction is in the mempool for at least 30
minutes and the fee increase does not exceed the maximum one allowed by the
Bridge. Given that the wallet is blocked with any other action until the sweep
transaction is in the mempool, the fee bump signing protocol retries until the
signature is produced or until the transaction is mined.

== Future Work

The link:https://github.com/keep-network/tbtc-v2/pull/374[sparse relay] provides
true proof of inclusion but requires every 6th block in the Bitcoin network to
be recorded on Ethereum. We started with a proof of work in tBTC v2 Bridge and
the light relay but one day we may switch to the sparse relay. This would allow
establishing a reference between a point in time on Ethereum and Bitcoin chains.
The reference point in time on Ethereum is a fixed block number - for example,
we sweep every 100th block - and the reference point in time on Bitcoin is the
last Bitcoin block recorded on Ethereum's sparse relay at the given Ethereum's
block number.
