:toc: macro

= RFC 9: Solana tBTC

:icons: font
:numbered:
toc::[]

== Background

There is a clear massive demand funnel present in Solana ecosystem for tBTC.
This RFC aims at providing a bespoke user experience for minting tBTC on Solana.

=== Current functionality

Even today it is possible to bridge tBTC to Solana with Wormhole. The whole user
experience is far from perfect, though. 

First, the user has to deposit their BTC using Threshold Dashboard on Ethereum.
This requires executing one Ethereum transaction. Next, once tBTC is minted on
Ethereum, the user has to go to the Wormhole Token Bridge portal and bridge
their Ethereum tBTC to Solana. This requires several transactions - one
transaction on Ethereum and several transactions on Solana. 

There is a significant cognitive effort on the user's side. Users are required
to use two applications and execute transactions on three networks: Bitcoin,
Ethereum, and Solana between them. Moreover, there is a period of time between
the time BTC was deposited and the time tBTC is minted on Ethereum that requires
the user to wait idly before they can bridge their Ethereum tBTC to Solana.

== Proposal

=== Goal

Users should mint tBTC on Solana in the Threshold Dashboard with two
transactions: one transaction on BTC and one transaction on Solana.

The redemption process should require just one Solana transaction from the user
executed in the Threshold Dashboard.

=== Implementation

The implementation is based on the Wormhole token bridge and does not require
the off-chain client to work with Solana. Ethereum L1 `Bank` contract remains
the center of the gravity of tBTC bridge and tBTC token is still minted
"centrally" on Ethereum L1.

==== P2SH deposit script

The P2SH deposit script has to be enhanced to include the vault address. As of
today, we expect the BTC transaction to be revealed to the Bridge by the same
Ethereum address as included in the P2SH deposit script. This prevents
front-running attacks but is not flexible enough. Allowing anyone to reveal the
Bitcoin deposit allows delegating this responsibility to the Wormhole relayer
bot.

```
<depositor-address> DROP
<vault-address> DROP
<blinding-factor> DROP
DUP HASH160 <signingGroupPubkeyHash> EQUAL
IF
  CHECKSIG
ELSE
  DUP HASH160 <refundPubkeyHash> EQUALVERIFY
  <locktime> CHECKLOCKTIMEVERIFY DROP
  CHECKSIG
ENDIF
```