:toc: macro

= RFC 1: tBTCv2 Design

:icons: font
:numbered:
toc::[]

== Overview

=== Minting

Stakers periodically create 51-of-100 ecdsa-backed wallets to hold frozen BTC
assets to maintain the peg. Depositors send BTC funds to the
most-recently-created-wallet by using pay-to-script-hash (P2SH) which contains
hashed information about the depositor's minting ethereum address. Once
the block is mined, the depositor reveals their desired ethereum minting
address to the ethereum chain. The TBTC system listens for these sorts of
messages and when it gets one, it checks the bitcoin network to make sure the
funds line up. If everything checks out, then we mint!

=== Redemption

A user supplies tBTCv2 and a bitcoin address. The system burns the tBTCv2 and
releases the equivalent amount of bitcoin to the user from the oldest
outstanding bitcoin wallet. If the oldest does not have enough, the remaining
balance carries over to the next oldest until an equivalent amount of BTC has
been released.

== In Depth

=== Minting

==== Deposit + Commitment

Once we know the active wallet's public key hash, the dApp can put together a
pay-to-script-hash (P2SH) address to receive the funds. This script will be
unique to each depositor and will look like:
```
if(verifySig(signingGroupPubKey) && hash160(ethereumAddress + blindingFactor)) {
    // allow funds to be spent
} else if(verifySig(refundPubKey) && daysSinceUTXOCreation > 30) {
    // allow funds to be spent
}
```

// TODO: represent the above script in the bitcoin scripting language and prototype it

Since each depositor has their own ethereum address and their own secret
blinding factor (which is an additional security layer), each depositor's
script will be unique, and the hash of each depositor's script will be unique.

Once the deposit has been made, the active wallet will be unable to spend the
funds until the ethereumAddress and blinding factor are revealed.

After 30 days, the refund wallet (specified by the user) will be able to spend the funds.

==== The Big Reveal

After the deposit transaction has been mined, the user is able to reveal their
ethereum address and blinding factor to the ethereum chain. The TBTC system listens
for these sorts of messages and when it sees one, is able to generate a script that
can spend the funds. Once successful, wallet moves the funds from the P2SH
address to the main wallet address, which allows the system to mint tBTC and
disables the 30-day refund.

==== Automated Refunds

A bitcoin transaction is an amount and a script. The script can be something as
simple as "these funds can be spent by wallet 0xabc", or in our case, as
complex as "these funds can be spent by wallet 0xabc but if they aren't spent
within 30 days they can be spent by wallet 0x123". This gives us the ability to
create deposits that automatically are refunded after 30 days if they aren't
swept. Thus, if a user misfunds or they get cold feet (for any reason), all
they need to do is not submit their reveal and wait 30 days.

=== Redemption

To initiate a redemption, a user supplies an amount `x` of TBTC and a bitcoin
address. Then, the system calculates the redemption fee `fee`, and releases an
amount of bitcoin `y` such that `x = y + fee` to the supplied bitcoin address.
`y` amount of TBTC is burned to maintain the peg. The remaining `fee` TBTC is
sold by the system to buy back `T` tokens (more about this process in the fee
section).

Redemptions for BTC follow first-in-first-out principles. Reedemed bitcoin is
sent from the oldest, live wallet, potentially carrying over until the full
amount is covered. For example, if 100 BTC needs to be redeemed, and the 4
oldest live wallets each have a 30 BTC balance, then 30 BTC would come from the
oldest, 30 BTC would come from the second oldest, 30 BTC would come from the
third oldest, and 10 BTC would come from the 4th oldest. Wallets that no longer
have a balance and are not the active wallet for deposits are effectively archived.

=== Wallet Lifecycle

Wallets are periodically created, where the period length is a governable
parameter. To create a new wallet, a group of 100 operators is selected from
the pool of available operators (some operators may be selected twice if there
are not enough) using a process called sortition. The probabiliy that a
particular operator is chosen is based on their stake weight, which in turn is
based on the number of `T` tokens they have invested in the staking contract.

Once the 100 operators have been selected, they generate a 51-of-100 ecdsa
signing group to handle the bitcoin key material. The distributed key
generation process requires that all 100 participants are available, but future
signing events (like minting and redemption) only require 51 of the 100.

As time passes and operators drop out of the system, a wallet becomes at risk of
being able to meet the 51-of-100 threshhold to produce signatures. Additionally,
we want to avoid situations where operators are the custodians of a wallet for
extended periods. To avoid these issues, we can set a max age of a wallet and a minimum
liveness threshhold. Once a wallet is older than the max age, or if it drops below
the liveness threshhold (say, below 60 on a heartbeat), we motion to transfer
the funds to another randomly selected wallet.

Once a wallet no longer has funds and is not the primary wallet for new
deposits, it can be archived and operators are no longer required to maintain
it.

=== Heartbeats

To make sure that older wallets are still accessible for redemption, we need to
perform heartbeats. This can take the form of small, cheap work that can be
used to verify that a node is still able to provide its part in a 51-of-100
signing event.

// FIXME: figure out how this works
